### ISSUE TITLE
building pytorch for arm without raspberry pi

### ISSUE THREAD

**Issue by ghost** [Ben-Faessler/Python3-Wheels#1]
@Ben-Faessler 
I have noticed your pytorch raspi build inwhich I am sure that took you many hours to build.
The thing is that you can emulate the arm board, and then build the code on it, it will be very fast!
https://nmilosev.svbtle.com/compling-arm-stuff-without-an-arm-board-build-pytorch-for-the-raspberry-pi

waiting for your reply

**Comment by deepseek** [comment]
https://choonkiatlee.github.io/posts/00002-raspbian-qemu/
https://github.com/choonkiatlee/qemu-raspbian

**Comment by Ben-Faessler** [comment]
Thanks for Note and the Info😀.

When will you link it?

deepseek <notifications@github.com> schrieb am Mo., 4. Mai 2020, 22:58:

**Comment by deepseek** [comment]
> When will you link it?

link what?

**Comment by Ben-Faessler** [comment]
My Repo with the wheel

deepseek <notifications@github.com> schrieb am Di., 5. Mai 2020, 18:22:

**Comment by deepseek** [comment]
I don't understand, but hey, good luck
