### ISSUE TITLE
Put .zip files

### ISSUE THREAD

**Issue by singhkpratham** [Ben-Faessler/Python3-Wheels#2]
Hello, 
I installed torch on my RPi4 using your wheels, and it really worked without any hassle! Thanks a lot.

However, I would suggest to rather upload the files in a .zip archive. It took me another 5 minutes to download and figure out p7zip.

**Comment by Ben-Faessler** [comment]
I cant upload a zip archive, the wheel is to big.
But when you will i can upload the wheel on One Drive.
Please write a answer.

**Comment by torchsmoke** [comment]
I cant upload the wheel in a zip archive. It is too big.
