### ISSUE TITLE
Provide instructions on how to install your prebuilt binaries

### ISSUE THREAD

**Issue by LearnedVector** [Ben-Faessler/Python3-Wheels#3]
Hello, thanks for your work. can you provide instructions on how to install this with your repo? Still trying to figure it out right now.

**Comment by LearnedVector** [comment]
Another question. Does this work for raspbian only? or can this work for ubuntu on rpi 4?

**Comment by torchsmoke** [comment]
I think that will work, but I haven't tried it yet. I added a instrution.
